name: Kernel
version: 1.0
main: com.example.kernel.Kernel
api-version: 1.13
depend: [LuckPerms, PlaceholderAPI]
commands:
  broadcast:
    description: Broadcast a message to all players.
    permission: kernel.broadcast
    aliases: [bc]
  playtime:
    description: Check how long you or another player has played on the server.
  day:
    description: Sets the time to day
    permission: kernel.time.day
  night:
    description: Sets the time to night
    permission: kernel.time.night
  vanish:
    description: Vanish from other players
    permission: kernel.vanish
  god:
    description: Toggle god mode
    permission: kernel.god
  scale:
    description: Set the scale of a player
    permission: kernel.scale
  chat:
    description: Chat control commands
    permission: kernel.chat
  rank:
    description: Manage player ranks
    permission: kernel.rank
  gm:
    description: Set gamemode
    permission: kernel.gamemode
    aliases: [gamemode]
  gmc:
    description: Set gamemode to creative
    permission: kernel.gamemode.creative
  gms:
    description: Set gamemode to survival
    permission: kernel.gamemode.survival
  gmsp:
    description: Set gamemode to spectator
    permission: kernel.gamemode.spectator
  gma:
    description: Set gamemode to adventure
    permission: kernel.gamemode.adventure
  cleardrops:
    description: Clear all dropped items from the server
    permission: kernel.cleardrops
  feed:
    description: Fill a player's hunger bar
    permission: kernel.feed
  heal:
    description: Heal a player and fill their hunger bar
    permission: kernel.heal
  speed:
    description: Set a player's walking or flying speed
    permission: kernel.speed
  metrics:
    description: Display server metrics and performance information
    permission: kernel.metrics
  list:
    description: Display online players grouped by rank
    permission: kernel.list
  getpos:
    description: Get a player's position
    permission: kernel.getpos
    aliases: [coords]
  tab:
    description: Reload tab display
    permission: kernel.tab.reload